"""같은 compiled rules를 호스트별 얇은 문서 형식으로 내보낸다."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable

from xout.atomic import atomic_write_text
from xout.compiler import (
    DEFAULT_RULE_LANG,
    XOUT_DOC,
    compile_rules,
    default_base_dir,
    render_xout_md,
)
from xout.locking import target_lock
from xout.own import fold_own_lines

FORMAT_MARKDOWN = "markdown"
FORMAT_AGENTS = "agents"
FORMAT_CLAUDE = "claude"
FORMAT_JSON = "json"
EXPORT_FORMATS = (FORMAT_MARKDOWN, FORMAT_AGENTS, FORMAT_CLAUDE, FORMAT_JSON)


def render_export(events: Iterable[Any], format_name: str, lang: str = DEFAULT_RULE_LANG) -> str:
    stream = tuple(events)
    rules = compile_rules(stream, lang=lang)
    own_lines = fold_own_lines(stream)
    if format_name == FORMAT_MARKDOWN:
        return render_xout_md(rules, lang, own_lines)
    if format_name in (FORMAT_AGENTS, FORMAT_CLAUDE):
        title = "Agent Instructions" if format_name == FORMAT_AGENTS else "Claude Instructions"
        body = "\n".join(f"- {rule.text}" for rule in rules)
        if own_lines:
            doc = XOUT_DOC.get(lang) or XOUT_DOC[DEFAULT_RULE_LANG]
            own_body = "\n".join(f"- {own.text}" for own in own_lines)
            body = f"{body}\n\n{doc['own']}\n\n{doc['own_intro']}\n\n{own_body}"
        return f"# {title}\n\n<!-- Generated by xout; edit the event stream, not this file. -->\n\n{body}\n"
    if format_name == FORMAT_JSON:
        return (
            json.dumps(
                {
                    "artifact": "popper_rules_export",
                    "format": FORMAT_JSON,
                    "rules": [rule.to_dict() for rule in rules],
                    "own_lines": [own.to_dict() for own in own_lines],
                },
                ensure_ascii=False,
                indent=2,
                sort_keys=True,
            )
            + "\n"
        )
    raise ValueError(f"지원하지 않는 export 형식: {format_name!r}")


def write_export(path: Path | str, body: str, base_dir: Path | str | None = None) -> Path:
    target = Path(path).expanduser().resolve()
    with target_lock(target, default_base_dir() if base_dir is None else base_dir):
        return atomic_write_text(target, body)
